author: "Anders Holmgren <andersmholmgren@gmail.com>"
description: "A shelf handler for authentication and authorisation"
homepage: "https://bitbucket.org/andersmholmgren/shelf_auth"
name: "shelf_auth"
version: "0.7.3"
dependencies:
  crypto: ">=0.9.2 <2.0.0"
  dart_jwt: "^0.5.1"
  http_exception: "^0.1.0"
  matcher: "^0.12.0"
  option: "^1.1.0"
  shelf: "^0.6.2"
  shelf_path: "^0.1.8"
  uuid: ">=0.4.0 <0.6.0"
dev_dependencies: 
  mock: ">=0.11.0+1 <0.13.0"
  mockito: ">=0.11.0 <0.12.0"
  shelf_exception_handler: ">=0.1.0"
  shelf_route: "^0.14.2"
  test: "^0.12.0"

environment:
  sdk: ">=1.13.0 <2.0.0"
