author: "Anders Holmgren <andersmholmgren@gmail.com>"
description: "A shelf handler for authentication and authorisation"
homepage: "https://bitbucket.org/andersmholmgren/shelf_auth"
name: "shelf_auth"
version: "0.7.1"
dependencies: 
  crypto: ">=0.9.0 <0.10.0"
  http_exception: "^0.1.0"
  matcher: "^0.12.0"
  shelf: "^0.6.2"
  uuid: ">=0.4.0 <0.6.0"
  dart_jwt: 
    git: 
      ref: "6d9dca78927ee747fb3b0f1ab834d9e802cbd909"
      url: "git@bitbucket.org:aholmgren/dart_jwt.git"
  option: 
    git: 
      ref: "eacb98574a2be87455decd39596d1867ee4bc0cc"
      url: "git@github.com:Andersmholmgren/option.git"
  shelf_path: 
    git: 
      ref: "9087c6f8640afc005550e1ea7652e913287ff13e"
      url: "git@bitbucket.org:andersmholmgren/shelf_path.git"
dev_dependencies: 
  mock: ">=0.11.0+1 <0.13.0"
  mockito: ">=0.11.0 <0.12.0"
  shelf_exception_handler: ">=0.1.0"
  test: "^0.12.0"
  shelf_route: 
    git: 
      ref: "6941ac9b6333867677b7aba375a0f754d7f8d0f9"
      url: "git@bitbucket.org:andersmholmgren/shelf_route.git"
environment: 
  sdk: ">=1.8.0 <2.0.0"
