name: shelf_auth
version: 0.0.1
author: Anders Holmgren <andersmholmgren@gmail.com>
description: A shelf handler for authentication
homepage: https://bitbucket.org/andersmholmgren/shelf_auth
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  option: any
  shelf: '>=0.5.1 <0.6.0'
  shelf_exception_response: any
dev_dependencies:
  mock: any
  unittest: '>=0.10.1+2 <0.12.0'
