author: Anders Holmgren <andersmholmgren@gmail.com>
description: A shelf handler for authentication and authorisation
homepage: https://bitbucket.org/andersmholmgren/shelf_auth
name: shelf_auth
version: 0.6.6
dependencies: 
  crypto: '>=0.9.0 <0.10.0'
  dart_jwt: '^0.4.0'
  http_exception: '^0.1.0'
  matcher: '^0.12.0'
  option: '>=0.3.3 <1.2.0'
  shelf: '^0.6.0'
  uuid: '>=0.4.0 <0.6.0'
  shelf_path: 
    git: 
      ref: 060318b435e847254e331cee5f24dd823dfac4a4
      url: git@bitbucket.org:andersmholmgren/shelf_path.git
dependency_overrides: 
dev_dependencies: 
  mock: '>=0.11.0+1 <0.13.0'
  mockito: '>=0.10.0 <0.11.0'
  shelf_exception_handler: '>=0.1.0'
  test: '^0.12.0'
  shelf_bind: 
    git: 
      ref: b5ad2e98986780fb1446403dc1a9b1c3563d500f
      url: git@bitbucket.org:andersmholmgren/shelf_bind.git
  shelf_route: 
    git: 
      ref: 7dca7ed8d2255a2e522705a0ad906323f874152a
      url: git@bitbucket.org:andersmholmgren/shelf_route.git
environment: 
  sdk: '>=1.8.0 <2.0.0'
