author: Anders Holmgren <andersmholmgren@gmail.com>
description: A shelf handler for authentication and authorisation
homepage: https://bitbucket.org/andersmholmgren/shelf_auth
name: shelf_auth
version: 0.6.8
dependencies: 
  crypto: '>=0.9.0 <0.10.0'
  http_exception: '^0.1.0'
  matcher: '^0.12.0'
  option: '>=0.3.3 <1.2.0'
  shelf: '^0.6.2'
  uuid: '>=0.4.0 <0.6.0'
  dart_jwt: 
    git: 
      ref: a26432534f1d7cd04f5c16861546d57ae4451889
      url: git@bitbucket.org:aholmgren/dart_jwt.git
  shelf_path: 
    git: 
      ref: 65dbbd7126d99512038a16d03a04daabc5ab1196
      url: git@bitbucket.org:andersmholmgren/shelf_path.git
dependency_overrides: 
dev_dependencies: 
  mock: '>=0.11.0+1 <0.13.0'
  mockito: '>=0.10.0 <0.11.0'
  shelf_exception_handler: '>=0.1.0'
  test: '^0.12.0'
  shelf_route: 
    git: 
      ref: 78f34091b697ea7756cd2dd999b44bc0d011c910
      url: git@bitbucket.org:andersmholmgren/shelf_route.git
environment: 
  sdk: '>=1.8.0 <2.0.0'
