author: "Anders Holmgren <andersmholmgren@gmail.com>"
description: "A shelf handler for authentication and authorisation"
homepage: "https://bitbucket.org/andersmholmgren/shelf_auth"
name: "shelf_auth"
version: "0.7.4"
dependencies:
  pointycastle:
    git:
      url: https://github.com/PointyCastle/pointycastle.git
      ref: 00c64f2ba8e5faa180f6e2d04653df70bb37b0b9
  http_exception: "^0.1.0"
  matcher: "^0.12.0"
  option: "^1.1.0"
  shelf: 
  shelf_path: 
  uuid: 
dev_dependencies:
  mock: ">=0.11.0+1 <0.13.0"
  mockito: ">=0.11.0 <0.12.0"
  shelf_exception_handler: ">=0.1.0"
  shelf_route: "^0.14.3"
  test: "^0.12.0"
environment:
  sdk: ">=1.16.0 <2.0.0"
