author: "Anders Holmgren <andersmholmgren@gmail.com>"
description: "A shelf handler for authentication and authorisation"
homepage: "https://bitbucket.org/andersmholmgren/shelf_auth"
name: "shelf_auth"
version: "0.7.0"
dependencies: 
  crypto: ">=0.9.0 <0.10.0"
  http_exception: "^0.1.0"
  matcher: "^0.12.0"
  option: ">=0.3.3 <1.2.0"
  shelf: "^0.6.2"
  uuid: ">=0.4.0 <0.6.0"
  dart_jwt: 
    git: 
      ref: "c657a14ec9fdfb6ae73f7e19afeeb57bf985595d"
      url: "git@bitbucket.org:aholmgren/dart_jwt.git"
  shelf_path: 
    git: 
      ref: "f78020ac323436fe18bbc1e154adb669deec93c3"
      url: "git@bitbucket.org:andersmholmgren/shelf_path.git"
dev_dependencies: 
  mock: ">=0.11.0+1 <0.13.0"
  mockito: ">=0.10.0 <0.11.0"
  shelf_exception_handler: ">=0.1.0"
  test: "^0.12.0"
  shelf_route: 
    git: 
      ref: "b0acf60578d1a5bef279f7878330a9a36ecb4e90"
      url: "git@bitbucket.org:andersmholmgren/shelf_route.git"
environment: 
  sdk: ">=1.8.0 <2.0.0"
